apiVersion: v1
kind: Service
metadata:
  name: result-app
spec:
  selector:
    app: result-app-frontend
  type: LoadBalancer
  ports:
  - name: result-app
    protocol: TCP
    port: 8081
    targetPort: 80
