apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  labels:
    app: voting-app-frontend
spec:
  selector:
    matchLabels:
      app: voting-app-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: voting-app-frontend
    spec:
       containers:
        - name:  voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
              name: voting-app
