apiVersion: v1
kind: Service
metadata:
  name: voting-app
spec:
  selector:
    app: voting-app-frontend
  type: LoadBalancer
  ports:
  - name: voting-app
    protocol: TCP
    port: 8080
    targetPort: 80

